package com.hooni.quotesaver.util

import com.hooni.quotesaver.R

const val NUMBER_OF_QUOTES_RETURNED_AT_ONCE = 30
const val DOUBLE_BACK_TAP_EXIT_INTERVAL = 2000

val backgroundImages = listOf(
    R.drawable.background_1,
    R.drawable.background_2,
    R.drawable.background_3,
    R.drawable.background_4,
    R.drawable.background_5,
    R.drawable.background_6,
    R.drawable.background_7,
    R.drawable.background_8,
    R.drawable.background_9,
    R.drawable.background_10,
    R.drawable.background_11,
    R.drawable.background_12,
    R.drawable.background_13,
    R.drawable.background_14,
    R.drawable.background_15,
    R.drawable.background_16,
    R.drawable.background_17,
    R.drawable.background_18,
    R.drawable.background_19,
    R.drawable.background_20,
    R.drawable.background_21,
    R.drawable.background_22,
    R.drawable.background_23,
    R.drawable.background_24,
    R.drawable.background_25,
    R.drawable.background_26,
    R.drawable.background_27,
    R.drawable.background_28,
    R.drawable.background_29,
    R.drawable.background_30,
)

val firstTimeSearches = listOf(
    "beautiful",
    "blessed",
    "creativity",
    "dream",
    "empowering",
    "family",
    "friendship",
    "fun",
    "funny",
    "generous",
    "genius",
    "gifted",
    "great",
    "happy",
    "healing",
    "hope",
    "hug",
    "innovative",
    "inspiring",
    "intelligence",
    "joy",
    "joyful",
    "kind",
    "kiss",
    "laugh",
    "laughter",
    "love",
    "lovely",
    "positive",
    "smart",
    "smile",
    "soul",
    "success",
    "trust",
    "wonderful"
)